### ISSUE TITLE
Co-location compiler may not work with pods or TypeScript?

### ISSUE THREAD

**Issue by chancancode** [ember-cli/ember-cli-htmlbars#308] opened 2019-09-26 21:02 UTC
Do we intend to make it work? If not it should error.

**Comment by josemarluedke** [comment] 2019-09-26 21:14
One of the nice things about co-location is that we see a future without pods. For folks already using pods, migrating to co-location components would feel like home, but if Ember requires to choose one or the other, pods would still be chosen instead of co-location. 

I believe that migrating to co-location when using pods is a small lift, but it would be a very hard sell if Ember would be required to move routes, controller, templates from pods to classic just to get co-location.

**Comment by rwjblue** [comment] 2019-09-27 13:22
The issue here is that its just not clear what to specifically do. I think that we should not break if pods are used, but I do not think that pods themselves should be allowed to use colocation.

@josemarluedke - Can you share some examples from your app of how you are using pods? It would be really useful to have some real-world examples to use for test cases for the broccoli-plugin (I'm mostly looking for file layout, not the contents of your components and whatnot).

**Comment by josemarluedke** [comment] 2019-09-27 15:28
[Here](https://gist.github.com/josemarluedke/dea77bf622cc8c871a2094f469def921) is the tree structure of an app using pods. [Here](https://gist.github.com/josemarluedke/12845ba59ac40da525c599c69b09188b) is the same app but using co-location for components and pods for the rest. Note we would use the nested file structure for co-location as we have related files to components like styles, graphql queries, etc.

**Comment by rwjblue** [comment] 2019-09-27 19:32
Thank you! Is there a specific issue you hit when interoping today? As in, if you move a single component to be colocated what happens? Does it work, does it error, etc?

**Comment by josemarluedke** [comment] 2019-09-27 22:53
@rwjblue As I mentioned in https://github.com/emberjs/ember.js/issues/18350#issuecomment-536120078, by moving one component to co-location, it won't render anymore.

**Comment by rwjblue** [comment] 2019-09-28 01:59
Hmm. Ok. I’ll spend some time trying to reproduce, but if others have a demo repo that shows the issue that would be helpful. There may be one in emberjs/ember.js#18350, will double check.

**Comment by chancancode** [comment] 2019-09-28 03:41
https://github.com/ember-learn/super-rentals-tutorial/pull/72 seems to have confirmed that there are no issues with pods. @josemarluedke did some more digging, and the problem may have to do with TypeScript instead.

**Comment by chancancode** [comment] 2019-09-28 03:41
If you are running into issues, a good thing to do may be to fork https://github.com/chancancode/super-rentals-pods-ish/ and try to reproduce the problem.

**Comment by rwjblue** [comment] 2019-09-30 13:06
Ya, we really need a reproduction in order to dig in. There are many variations of "pods" and folks tend to all be talking about different things, making it very hard to actually dig into...

**Comment by josemarluedke** [comment] 2019-09-30 18:00
It seems this issue is not related to pods after all, just TypeScript. My original urge to comment here was because I tested in an app using pods and typescript (which is were I saw errors). Testing out with super-rentals-pods-ish showed that there was no issues in pods with co-location. Both seem to work well together. Thanks @chancancode for putting that together, it really helped.

The issue I have seem to be present only when a decorator is applied to a co-located component when the project has TypeScript, independent if the component is JS or TS. I have a [fork of super-rentals-pods-ish](https://github.com/josemarluedke/super-rentals-pods-ish) showing the problem. The component "other" won't render anything.

Below are 2 screenshots of the compiled component JS file, one **not** using TypeScript and the other using it.

 ### When TypeScript was not installed in the project
![Screen Shot 2019-09-27 at 6 00 58 PM](https://user-images.githubusercontent.com/230476/65902452-534de680-e36f-11e9-96d0-16a509369d19.png)

Correspondent commit: https://github.com/josemarluedke/super-rentals-pods-ish/commit/a5536151f9b9c37fd56f5bcb3e36dc103a45e190


### When TypeScript was installed in the project
![Screen Shot 2019-09-30 at 10 48 04 AM](https://user-images.githubusercontent.com/230476/65902765-f7d02880-e36f-11e9-91bb-8fca78c6500b.png)

Correspondent commit: https://github.com/josemarluedke/super-rentals-pods-ish/commit/54464c0d6de9b729ed96dc584dcba966c1daf16c

**Comment by lolmaus** [comment] 2019-09-30 18:04
@josemarluedke Could be related to this: https://github.com/typed-ember/ember-cli-typescript/issues/724

**Comment by rwjblue** [comment] 2019-10-17 21:47
I suspect that https://github.com/ember-cli/ember-cli-htmlbars/pull/333 will fix this, but if not it at least should make it easier to dig in to what is going on.

**Comment by rwjblue** [comment] 2019-10-17 23:37
OK, #333 is released in 4.0.6 please test and confirm it that fixes these issues...

**Comment by josemarluedke** [comment] 2019-10-18 00:16
I just tested this out and it did not solve the issue. See reproduction repo here: 
https://github.com/josemarluedke/super-rentals-pods-ish

**Comment by HenryVonfire** [comment] 2019-10-18 07:49
I found the same issue and reported it in `ember-cli-typescript` [here](https://github.com/typed-ember/ember-cli-typescript/issues/906).

[here](https://github.com/HenryVonfire/colocation-bug) is a super basic repository with the issue. It has just a colocated component with a tracked property. If you run the project the component is not rendered. If you remove the tracked property it works.

**Comment by rwjblue** [comment] 2019-10-18 19:20
Thanks to @dfreeman, @HenryVonfire, and @josemarluedke, this should now be fixed and released in [v4.0.7](https://github.com/ember-cli/ember-cli-htmlbars/releases/tag/v4.0.7).

Please test / confirm, then I'll close this issue...

**Comment by josemarluedke** [comment] 2019-10-18 22:00
I just confirmed that v4.0.7 did fix the issues I have been seeing. Thanks, @dfreeman, @HenryVonfire, @rwjblue.

**Closed** 2019-10-18 23:16 UTC
