### ISSUE TITLE
Deprecation warning due to not calling super init

### ISSUE THREAD

**Issue by joelpresence** [ember-cli/ember-cli-htmlbars#107] opened 2017-01-11 22:46 UTC
```
DEPRECATION: Overriding init without calling this._super is deprecated.
Please call `this._super.init && this._super.init.apply(this, arguments);`
addon: `ember-cli-htmlbars`
```

**Comment by kellyselden** [comment] 2017-01-11 23:44
Duplicate of #77

**Closed by kellyselden** 2017-01-11 23:44 UTC

**Comment by joelpresence** [comment] 2017-01-11 23:47
Please see my comments on 77 @kellyselden .  Thanks!
